### ISSUE TITLE
Getting Ready for Publishing v0.1.0

### ISSUE THREAD

**Issue by rhamzeh** [openfga/intellij-plugin#1]
- [x] Update ownership references to OpenFGA https://github.com/openfga/intellij-plugin/pull/9
- [x] Add CODEOWNER
- [x] Update README
  - [x] Credit @le-yams and reference the original repo
  - [x] Match the templates we use for OpenFGA
  - [x] Add screenshots and a list of the currently supported features
- [x] Security and Licensing
  - [x] Configure snyk
  - [x] Configure Semgrep
  - [x] Configure dependabot
  - [x] Configure FOSSA
  - [x] Setup EasyCLA (can only be done after the repo is public)
- [x] CI
  - [x] Expand the test matrix used to include more IDEs
  - [x] Add a release and publishing step
- [x] Admin
  - [x] Create the org on Jetbrains marketplace
  - [x] Set registry token
  - [x] Set branch protection for main

**Comment by d-jeffery** [comment]
Expand the test matrix used to include more IDEs

https://github.com/openfga/intellij-plugin/pull/14

**Comment by d-jeffery** [comment]
Release and Publishing workflow

https://github.com/openfga/intellij-plugin/pull/15
