### ISSUE TITLE
'x' not a valid type highlighting key, not field, when same name.

### ISSUE THREAD

**Issue by d-jeffery** [openfga/intellij-plugin#47]
```
  model
    schema 1.1

  type employee
  type custome
  type bank
    relations
      define customer : [customer]
      define account_manager : [employee]
```

<img width="348" alt="image" src="https://github.com/user-attachments/assets/bfca4028-a849-4122-a651-c1ae4fe61f68">

**Comment by d-jeffery** [comment]
The above is a **SyntaxError** - might be that syntax errors in language are not 0 based.

**Comment by d-jeffery** [comment]
Confirming that java implementation of **SyntaxError** is 1 based, with no adjustment.

https://github.com/openfga/language/blob/main/pkg/java/src/main/java/dev/openfga/language/OpenFgaDslErrorListener.java#L25-L27

**Comment by d-jeffery** [comment]
Duplicate of: https://github.com/openfga/language/issues/259

**Comment by ewanharris** [comment]
Validated as fixed by language upgrade
