### ISSUE TITLE
Duplicate defines under a type do not highlight correct text

### ISSUE THREAD

**Issue by d-jeffery** [openfga/intellij-plugin#48]
<img width="348" alt="image" src="https://github.com/user-attachments/assets/28734076-0def-4a9e-a012-85be85a45ce5">

**Comment by d-jeffery** [comment]
The above is a **SyntaxError** - might be that syntax errors in language are not 0 based.

**Comment by d-jeffery** [comment]
Confirming that java implementation of **SyntaxError** is 1 based, with no adjustment.

https://github.com/openfga/language/blob/main/pkg/java/src/main/java/dev/openfga/language/OpenFgaDslErrorListener.java#L25-L27

**Comment by d-jeffery** [comment]
Should be fixed once https://github.com/openfga/language/commit/eb1335af2891d24e6be31c932d0023fadcab466a is released and adopted.

**Comment by ewanharris** [comment]
Validated as fixed by language upgrade
